---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-app-example
spec:
  selector:
    matchLabels:
      app: greeting-app-example
  template:
    metadata:
      labels:
        app: greeting-app-example
    spec:
      containers:
      - name: greeting-app-example
        # to make sure new pipeline builds gets new image always
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
